name: chain_sentinel
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - affine=2.3.0
  - aiofiles=0.4.0
  - aniso8601=7.0.0
  - appdirs=1.4.3
  - asciitree=0.3.3
  - asn1crypto=1.3.0
  - aspy.yaml=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - blinker=1.4
  - bokeh=1.4.0
  - boto3=1.11.0
  - botocore=1.14.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cached-property=1.5.1
  - cachetools=3.1.1
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cfgv=2.0.1
  - cfitsio=3.470
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - colorcet=2.0.2
  - coverage=5.0
  - cryptography=2.8
  - curl=7.67.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.9.1
  - dask-core=2.9.1
  - datashader=0.9.0
  - datashape=0.5.4
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - distributed=2.9.1
  - docopt=0.6.2
  - docutils=0.15.2
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.2.6
  - fastapi=0.46.0
  - fasteners=0.15
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - fsspec=0.6.2
  - gcsfs=0.6.0
  - gdal=2.3.3
  - geopandas=0.6.1
  - geos=3.7.1
  - geoviews=1.6.5
  - geoviews-core=1.6.5
  - giflib=5.1.4
  - glib=2.63.1
  - google-auth=1.10.2
  - google-auth-oauthlib=0.4.1
  - graphene=2.1.8
  - graphql-core=2.2
  - graphql-relay=2.0.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h11=0.8.1
  - h5py=2.9.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - holoviews=1.12.7
  - httptools=0.0.13
  - icu=58.2
  - identify=1.4.11
  - idna=2.8
  - imageio=2.6.1
  - importlib_metadata=1.4.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jasper=1.900.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jmespath=0.9.4
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.5
  - jupyterlab_server=1.0.6
  - kealib=1.4.7
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libboost=1.67.0
  - libcurl=7.67.0
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=2.3.3
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.31.0
  - locket=0.2.0
  - lxml=4.4.2
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - monotonic=1.5
  - more-itertools=8.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.3
  - ncurses=6.1
  - netcdf4=1.4.2
  - networkx=2.4
  - nodeenv=1.3.4
  - notebook=6.0.1
  - numba=0.47.0
  - numcodecs=0.6.4
  - numpy-base=1.17.4
  - oauthlib=3.0.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1d
  - owslib=0.18.0
  - packaging=20.0
  - pandas=0.25.3
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - param=1.9.2
  - parso=0.5.2
  - partd=1.1.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.3.1
  - pixman=0.38.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - pre_commit=1.18.1
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - promise=2.2.1
  - prompt_toolkit=3.0.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pyct=0.4.6
  - pydantic=1.4
  - pyepsg=0.4.0
  - pygments=2.5.2
  - pyhdf=0.10.2
  - pyjwt=1.7.1
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyorbital=1.5.0
  - pyparsing=2.4.6
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyresample=1.14.0
  - pyrsistent=0.15.7
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pyspectral=0.9.4
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-geotiepoints=1.1.8
  - python-multipart=0.0.5
  - pytz=2019.3
  - pyviz_comms=0.7.2
  - pywavelets=1.1.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - rasterio=1.0.21
  - readline=7.0
  - requests=2.22.0
  - requests-oauthlib=1.2.0
  - rsa=4.0
  - rtree=0.8.3
  - rx=3.0.1
  - s3fs=0.4.0
  - s3transfer=0.3.0
  - satpy=0.19.1
  - scikit-image=0.15.0
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=44.0.0
  - shapely=1.6.4
  - sip=4.19.8
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - sqlite=3.30.1
  - starlette=0.12.9
  - tbb=2018.0.5
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.6.3
  - tk=8.6.8
  - toml=0.10.0
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.41.1
  - traitlets=4.3.3
  - trollimage=1.11.0
  - trollsift=0.3.4
  - ujson=1.35
  - urllib3=1.25.7
  - uvicorn=0.9.1
  - uvloop=0.12.2
  - virtualenv=16.7.5
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websockets=7.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wsproto=0.13.0
  - xarray=0.14.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - zipp=1.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - configobj=
    - eccodes=
    - geojson=
    - geomet=
    - html2text=
    - libtiff=
    - numpy=
    - pyyaml=
    - sentinelsat=
    - six=

